# Generated by Django 4.2.7 on 2023-11-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(choices=[('Matematicas', 'Matematicas'), ('Back-end', 'Back-end'), ('Front-end', 'Front-end'), ('Nube', 'Nube'), ('Ingles', 'Ingles')], max_length=100),
        ),
    ]
