# Generated by Django 4.2.7 on 2023-11-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_materia_profesor_alter_materia_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='profesor',
        ),
    ]
