# Generated by Django 4.2.7 on 2023-11-28 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumno', '0003_alter_alumno_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=30)),
                ('contenido', models.TextField(default='', max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discusiones', to='alumno.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(default='', max_length=1000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='alumno.alumno')),
                ('discusion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='discusion.discusion')),
            ],
        ),
    ]
