# Generated by Django 4.2.7 on 2023-11-30 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discusion', '0004_remove_comentario_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discusion',
            name='fecha_creacion',
        ),
    ]
